### ISSUE TITLE
promenade generate-certs is failing with an error

### ISSUE THREAD

**Issue by pbelamge** [att-comdev/ucp-integration#19]
Trying to deploy ucp and getting an error:

Command:
**+ exec promenade generate-certs -o /target ArmadaManifest.yaml armada-resources.yaml Docker.yaml Genesis.yaml HostSystem.yaml joining-host-config.yaml Kubelet.yaml KubernetesNetwork.yaml**
.
.
.
2018-02-12 07:36:34,238 INFO     - - - promenade.config:__init__ [ 21] Parsing document schemas.
2018-02-12 07:36:34,239 INFO     - - - promenade.config:__init__ [ 23] Parsed 0 document schemas.
2018-02-12 07:36:34,239 INFO     - - - promenade.config:__init__ [ 24] Building config from 25 documents.
2018-02-12 07:36:34,239 INFO     - - - promenade.config:__init__ [ 26] Rendering documents via Deckhand engine.
2018-02-12 07:36:36,251 WARNING  - - - deckhand.engine.secrets_manager:substitute_all [188] Could not find substitution source document [deckhand/CertificateAuthority/v1] kubernetes among the provided `substitution_sources`.
**2018-02-12 07:36:36,251 ERROR    - - - deckhand.utils:jsonpath_replace [152] The provided jsonpath $.values.secrets.tls.ca does not begin with "."**
2018-02-12 07:36:36,251 ERROR    - - - deckhand.engine.secrets_manager:substitute_all [225] Unexpected exception occurred while attempting secret substitution. ('The provided jsonpath %s does not begin with "."', '$.values.secrets.tls.ca')
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/deckhand/engine/secrets_manager.py", line 212, in substitute_all
    document['data'], src_secret, dest_path, dest_pattern)
  File "/usr/local/lib/python3.6/site-packages/deckhand/utils.py", line 154, in jsonpath_replace
    jsonpath)
ValueError: ('The provided jsonpath %s does not begin with "."', '$.values.secrets.tls.ca')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/promenade", line 10, in <module>
    sys.exit(promenade())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/promenade/promenade/cli.py", line 59, in genereate_certs
    debug=debug, streams=config_files, substitute=True, validate=False)
  File "/opt/promenade/promenade/config.py", line 49, in from_streams
    return cls(documents=documents, **kwargs)
  File "/opt/promenade/promenade/config.py", line 29, in __init__
    documents = [dict(d) for d in deckhand_eng.render()]
  File "/usr/local/lib/python3.6/site-packages/deckhand/engine/layering.py", line 333, in render
    self.secrets_substitution.substitute_all(doc))
  File "/usr/local/lib/python3.6/site-packages/deckhand/engine/secrets_manager.py", line 226, in substitute_all
    raise errors.SubstitutionFailure(details=six.text_type(e))
deckhand.errors.SubstitutionFailure: An unknown exception occurred while trying to perform substitution. Details: %(detail)s

**Comment by sh8121att** [comment]
Thanks for reporting this - we have an outstanding patchset to fix this issue: https://review.gerrithub.io/399244. In the mean time, I believe Deckhand has added support for starting a path with`$` so you might want to retry ensuring you are using the latest Promenade image.
